--DELETE from source_target_match where source_datasetId ='laborder'

INSERT INTO source_target_match (source_datasetId, source_id, source_field, source_value, expected_mapped_value, 
target_id,
target_field, target_value, matched, notes)
SELECT 
  'laborder' as source_datasetId,
  source.uid as source_id, 
  match_tests.source_field, match_tests.source_value, match_tests.expected_mapped_value, 
  target._id as target_id,match_tests.target_field, match_tests.target_value,
  match_tests.expected_mapped_value is not distinct from match_tests.target_value as matched,match_tests.notes
FROM v_source_lab as source
FULL JOIN v_migrated_laborder as target ON source.uid = target.source_instanceId
CROSS JOIN LATERAL (VALUES
   ('patient',source.patient_src,source.patient_src,'patient_source_instanceid ', target.patient_source_instanceid, null),
    ('provider_uid',source.provider_src::text, source.provider_src::text, 'provider_source_instanceid', target.provider_source_instanceid::text, null),
	('location',source.location_src::text,source.location_src::text,'location_source_instanceid ', target.office_source_instanceid::text, null),
	('order_number',source.order_number,source.order_number,'orderNumber',target.orderNumber::text, null),
  ('order_status_name',source.order_status_name,source.order_status_name,'orderStatus',target.orderStatus::text, null),
  ('order_type',source.order_type::text,source.order_type::text,'orderType',target.orderType::text,null),
  --('',source.,source.,'itemSource',target.itemSource::text, null),
  ('quantity',source.quantity::text,source.quantity::text,'quantity',target.quantity::text, null),
  ('flags',source.flags::text,source.flags::text,'orderFlags',target.orderFlags::text, null),
  ('job_flags',source.job_flags::text,source.job_flags::text,'jobFlags1',target.jobFlags1::text, null),
  ('job_flags',source.job_flags::text,source.job_flags::text,'jobFlags2',target.jobFlags2::text, null),
  ('job_type',source.job_type::text,source.job_type::text,'jobType',target.jobType::text, null),
  ('notes',source.notes::text,source.notes::text,'notes',target.notes::text, null),
  ('auth',source.auth,source.auth,'auth',target.auth::text, null),
  ('history',source.history::text,source.history::text,'additionalProperties',target.additionalProperties::text, null),
  ('orderdate',source.orderdate::text,source.orderdate::text,'orderDate',target.orderDate::text, null),
  ('FRAME','FRAME','FRAME','itemType',target.itemType::text, null),
  ('sku_src',source.sku_src::text,source.sku_src::text,'sku',target.sku::text, null), 
  ('mfg_name',source.mfg_name::text,source.mfg_name::text,'manufacturerskuname',target.manufacturerskuname::text, null),
  ('mfg_nickname',source.mfg_name::text,source.mfg_name::text,'skunickName',target.skunickName::text, null),	   	  
  ('ed',source.ed::text,source.ed::text,'skued',target.skued::text, null), 
  ('b',source.b::text,source.b::text,'skub',target.skub::text, null), 
  ('dbl',source.dbl::text,source.dbl::text,'skudbI',target.skudbI::text, null),
  ('frame_type',source.frame_type::text,source.frame_type::text,'skutypeCode',target.skutypeCode::text, null), 
  ('eye_size',source.eye_size::text,source.eye_size::text,'skusize',target.skusize::text, null), 
  ('frame_name',source.frame_name::text,source.frame_name::text,'skuname',target.skuname::text, null), 
  ('temple',source.temple::text,source.temple::text,'skutemple',target.skutemple::text, null), 
  ('frames.retail',source.fprice::text,source.fprice::text,'skuRetailPrice',target.skuRetailPrice::text, null), 
  ('lensl.item_type alias itemtypelensl',source.itemtypelensl::text,source.itemtypelensl::text,'lenslitemType',target.lenslitemType::text, null),
  ('lenslsku',source.lensl::text,source.lensl::text,'lenslsku',target.lenslsku::text, null),
  ('lensritemtype',source.itemtypelensr::text,source.itemtypelensr::text,'lensRitemType',target.lensRitemType::text, null),
  ('lensr',source.lensr::text,source.lensr::text,'lensRsku',target.lensRsku::text, null),
  ('lensoptionsjson',source.lensoptionsjson::text,source.lensoptionsjson::text,'lensEnhansku',target.lensEnhansku::text, null),
  ('r_prism',source.r_prism::text,source.r_prism::text,'glrxprismosp1',target.glrxprismosp1::text, null),
  ('r_sph',source.r_sph::text,source.r_sph::text,'glrxodsphere',target.glrxodsphere::text, null),
  ('r_cyl',source.r_cyl::text,source.r_cyl::text,'glrxodcylinder',target.glrxodcylinder::text, null),
  ('r_axis',source.r_axis::text,source.r_axis::text,'glrxodaxis',target.glrxodaxis::text, null),
  ('r_add',source.r_add::text,source.r_add::text,'glrxodadd',target.glrxodadd::text, null),
  ('l_sph',source.l_sph::text,source.l_sph::text,'glrxossphere',target.glrxossphere::text, null),
  ('l_cyl',source.l_cyl::text,source.l_cyl::text,'glrxoscylinder',target.glrxoscylinder::text, null),
  ('r_add',source.r_add::text,source.r_add::text,'glrxosaxis',target.glrxosaxis::text, null),
  ('l_add',source.l_add::text,source.l_add::text,'glrxosadd',target.glrxosadd::text, null),
  ('rxstartdate',source.rxstartdate::text,source.rxstartdate::text,'glrxstartDate',target.glrxstartDate::text, null),	
  ('rxexpdate',source.rxexpdate::text,source.rxexpdate::text,'glrxexpirationDate',target.glrxexpirationDate::text, null),	
  ('provlastname',source.provlastname::text,source.provlastname::text,'glrxlasttName',target.glrxlastname::text, null),	
  ('provfirstname',source.provfirstname::text,source.provfirstname::text,'glrxfirstName',target.glrxfirstName::text, null),
  ('r_monopd_d',source.r_monopd_d::text,source.r_monopd_d::text,'measurement_odd',target.measurement_odd::text, null),
  ('r_monopd_n',source.r_monopd_n::text,source.r_monopd_n::text,'measurement_odn',target.measurement_odn::text, null),
  --('r_monopd_n',source.r_monopd_n,source.r_monopd_n,'measurementod_n',target.measurementod_n::text, null),
  ('r_ocheight',source.r_ocheight::text,source.r_ocheight::text,'measurementod_oc',target.measurementod_oc::text, null),
  ('r_decenter',source.r_decenter::text,source.r_decenter::text,'measurementod_dec',target.measurementod_dec::text, null),
  ('r_vd',source.r_vd::text,source.r_vd::text,'measurementod_vd',target.measurementod_vd::text, null),
  ('r_panto',source.r_panto::text,source.r_panto::text,'measurementod_panto',target.measurementod_panto::text, null),
  --('',source.,source.,'measurementod_wrap',target.measurementod_wrap::text, null),
  ('r_height',source.r_height::text,source.r_height::text,'measurementod_minSegHeight',target.measurementod_minSegHeight::text, null),
  ('l_monopd_d',source.l_monopd_d::text,source.l_monopd_d::text,'measurement_osd',target.measurement_osd::text, null),
  ('l_monopd_n',source.l_monopd_n::text,source.l_monopd_n::text,'measurement_osn',target.measurement_osn::text, null),
  ('l_ocheight',source.l_ocheight::text,source.l_ocheight::text,'measurementos_oc',target.measurementos_oc::text, null),
  ('l_decenter',source.l_decenter::text,source.l_decenter::text,'measurementos_dec',target.measurementos_dec::text, null),
  ('l_vd',source.l_vd::text,source.l_vd::text,'measurementos_vd',target.measurementos_vd::text, null),
  ('l_panto',source.l_panto::text,source.l_panto::text,'measurementos_panto',target.measurementos_panto::text, null),
  --('',source.,source.,'measurementos_wrap',target.measurementos_wrap::text, null),
  ('l_height',source.l_height::text,source.l_height::text,'measurementos_minSegHeight',target.measurementos_minSegHeight::text, null),
  ('rxstartdate',source.rxstartdate::text,source.rxstartdate::text,'measurementstartdate',target.measurementstartdate::text, null),
  ('rxexpdate',source.rxexpdate::text,source.rxexpdate::text,'measurementexpiredate',target.measurementexpiredate::text, null),
  ('provfirstname',source.provfirstname::text,source.provfirstname::text,'measurementprovider_firstName',target.measurementprovider_firstName::text, null),
  ('provlastname',source.provlastname::text,source.provlastname::text,'measurementprovider_LastName',target.measurementprovider_LastName::text, null),	  
  ('vendor_number',source.vendor_number::text,source.vendor_number::text,'lab_vendorNo',target.lab_vendorNo::text, null),
  ('lab_number',source.lab_number::text,source.lab_number::text,'labNumber',target.labNumber::text, null),
  ('outside_lab',source.outside_lab::text,source.outside_lab::text,'outsideLab',target.outsideLab::text, null)
		
 )as match_tests(source_field, source_value, expected_mapped_value, target_field, target_value, notes)
;