-- View: public.v_migrated_patients

-- DROP VIEW public.v_migrated_patients;

CREATE OR REPLACE VIEW public.v_migrated_patients
 AS
 SELECT o.source_datasetid,
    o.source_instanceid,
    o.target_model ->> '_id'::text AS _id,
    o.target_model ->> 'title'::text AS title,
    o.target_model ->> 'firstName'::text AS firstname,
    o.target_model ->> 'lastName'::text AS lastname,
    o.target_model ->> 'id'::text AS id,
    o.target_model ->> 'nickName'::text AS nickname,
    o.target_model ->> 'mrn'::text AS mrn,
    o.target_model ->> 'mi'::text AS mi,
    (o.target_model ->> 'dob'::text)::date AS dob,
    o.target_model ->> 'age'::text AS age,
    o.target_model ->> 'sex'::text AS sex,
    o.target_model ->> 'ssn'::text AS ssn,
    o.target_model ->> 'notes_text'::text AS notes_text,
    ((o.target_model -> 'address'::text) -> 0) ->> 'addressLine1'::text AS address_addressline1,
    ((o.target_model -> 'address'::text) -> 0) ->> 'city'::text AS address_city,
    ((o.target_model -> 'address'::text) -> 0) ->> 'state'::text AS address_state,
    ((o.target_model -> 'address'::text) -> 0) ->> 'zip'::text AS address_zip,
    ((o.target_model -> 'address'::text) -> 0) ->> 'isBadAddress'::text AS address_badaddress,
    ((o.target_model -> 'address'::text) -> 0) ->> 'ispreferred'::text AS address_ispreferred,
    o.target_model ->> 'contactPrefrence'::text AS contactprefrence,
    (o.target_model -> 'smokingHistory'::text) ->> 'smokingStatus'::text AS smokinghistory_smokingstatus,
    (o.target_model -> 'contactInformation'::text) ->> 'language'::text AS contactinformation_language,
    (o.target_model -> 'contactInformation'::text) ->> 'preferred'::text AS contactinformation_preferred,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 0) ->> 'type'::text AS contactinformation_homephone_type,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 1) ->> 'type'::text AS contactinformation_workphone_type,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 2) ->> 'type'::text AS contactinformation_cellphone_type,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 0) ->> 'phoneNumber'::text AS contactinformation_phones_homephonenumber,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 1) ->> 'phoneNumber'::text AS contactinformation_phones_workphonenumber,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 2) ->> 'phoneNumber'::text AS contactinformation_phones_cellphonenumber,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 0) ->> 'isPreferred'::text AS contactinformation_homephone_ispreferred,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 1) ->> 'isPreferred'::text AS contactinformation_workphone_ispreferred,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 2) ->> 'isPreferred'::text AS contactinformation_cellphone_ispreferred,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 0) ->> 'isBad'::text AS contactinformation_homephone_isbad,
	 (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 1) ->> 'isBad'::text AS contactinformation_workphone_isbad,
	  (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) -> 2) ->> 'isBad'::text AS contactinformation_cellphone_isbad,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) -> 0) ->> 'type'::text AS contactinformation_emails_type,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) -> 0) ->> 'email'::text AS contactinformation_emails_email,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) -> 0) ->> 'isPreferred'::text AS contactinformation_emails_ispreferred,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) -> 0) ->> 'badEmail'::text AS contactinformation_emails_bademail,
    (o.target_model -> 'contactInformation'::text) ->> 'noEmail'::text AS contactinformation_noemail,
    (o.target_model -> 'patientDetails'::text) ->> 'occupation'::text AS patientdetails_occupation,
    (o.target_model -> 'patientDetails'::text) ->> 'maritalStatus'::text AS patientdetails_maritalstatus,
    (o.target_model -> 'patientDetails'::text) ->> 'maidenName'::text AS patientdetails_maidenname,
    (o.target_model -> 'patientDetails'::text) ->> 'sexualOrientation'::text AS patientdetails_sexualorientation,
    (o.target_model -> 'patientDetails'::text) ->> 'genderIdentities'::text AS patientdetails_genderidentities,
    (o.target_model -> 'patientDetails'::text) ->> 'employer'::text AS patientdetails_employer,
    (o.target_model -> 'patientDetails'::text) ->> 'previousFirstName'::text AS patientdetails_previousfirstname,
    (o.target_model -> 'patientDetails'::text) ->> 'previousLastName'::text AS patientdetails_previouslastname,
    (o.target_model -> 'patientDetails'::text) ->> 'previousMiddleName'::text AS patientdetails_previousmiddlename,
    btrim((o.target_model -> 'patientDetails'::text) ->> 'race'::text, '[]'::text) AS patientdetails_race,
    btrim((o.target_model -> 'patientDetails'::text) ->> 'ethnicity'::text, '[]'::text) AS patientdetails_ethnicity,
    (o.target_model -> 'patientDetails'::text) ->> 'isFlagNew'::text AS patientdetails_isflagnew,
    (o.target_model -> 'patientDetails'::text) ->> 'isFlagInCollection'::text AS patientdetails_isflagincollection,
    (o.target_model -> 'patientDetails'::text) ->> 'isFlagBadCheck'::text AS patientdetails_isflagbadcheck,
    (o.target_model -> 'patientDetails'::text) ->> 'isFlagDeceased'::text AS patientdetails_isflagdeceased,
    (o.target_model -> 'patientDetails'::text) ->> 'isFlagChartless'::text AS patientdetails_isflagchartless,
    (o.target_model -> 'guarantor'::text) ->> 'firstName'::text AS guarantor_firstname,
    (o.target_model -> 'guarantor'::text) ->> 'lastName'::text AS guarantor_lastname,
    ((o.target_model -> 'guarantor'::text) ->> 'dob'::text)::date AS guarantor_dob,
    (o.target_model -> 'guarantor'::text) ->> 'maritalStatus'::text AS guarantor_maritalstatus,
    (o.target_model -> 'guarantor'::text) ->> 'middleName'::text AS guarantor_middlename,
    (o.target_model -> 'guarantor'::text) ->> 'relationship'::text AS guarantor_relationship,
    (o.target_model -> 'guarantor'::text) ->> 'releaseHippaInfo'::text AS guarantor_releasehippainfo,
    (o.target_model -> 'guarantor'::text) ->> 'sex'::text AS guarantor_sex,
    (o.target_model -> 'guarantor'::text) ->> 'ssn'::text AS guarantor_ssn,
    (o.target_model -> 'guarantor'::text) ->> 'title'::text AS guarantor_title,
    ((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'addressLine1'::text AS guarantor_address_addressline1,
    ((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'city'::text AS guarantor_address_city,
    ((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'state'::text AS guarantor_address_state,
    ((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'zip'::text AS guarantor_address_zip,
    ((((o.target_model -> 'guarantor'::text) -> 'contactInformation'::text) -> 'emails'::text) -> 0) ->> 'email'::text AS guarantor_contactinformation_email,
    ((((o.target_model -> 'guarantor'::text) -> 'contactInformation'::text) -> 'phones'::text) -> 0) ->> 'number'::text AS guarantor_contactinformation_homephone_number,
    ((((o.target_model -> 'guarantor'::text) -> 'contactInformation'::text) -> 'phones'::text) -> 1) ->> 'number'::text AS guarantor_contactinformation_workphone_number,
    ((((o.target_model -> 'guarantor'::text) -> 'contactInformation'::text) -> 'phones'::text) -> 2) ->> 'number'::text AS guarantor_contactinformation_cellphone_number
   FROM v_migrated_objects o
  WHERE o.model::text = 'patients'::text;

ALTER TABLE public.v_migrated_patients
    OWNER TO postgres;

