-- View: public.v_source_patients_new

-- DROP VIEW public.v_source_patients_new;

CREATE OR REPLACE VIEW public.v_source_patients
 AS
 SELECT p1.uid,
    p1.homephone,
    p1.workphone,
    p1.email,
    p1.cell,
    p1.designation,
    p1.firstname,
    p1.lastname,
    p1.pat_id,
    p1.preferred_name,
    p1.mi,
    p1.birthday,
    p1.sex AS sexs,
    p1.ssn AS ssn_src,
    p1.address,
    p1.city,
    p1.state,
    p1.zip,
    p1.bad_address,
    p1.smoking_status,
    p1.no_call,
    p1.ssn,
    p1.preferred_phone,
    p1.bad_phone,
    p1.employer,
    p1.previous_mi,
    p1.preferred_contact,
    p1.preferred_language,
    p1.occupation,
    p1.married,
    p1.maiden_name,
    p1.referral_source,
    p1.sexual_orientation,
    p1.gender_identity,
    p1.previous_firstname,
    p1.previous_lastname,
    p1.race,
    p1.ethnicity,
    p1.new_pat,
    p1.collections,
    p1.bad_check,
    p1.chartless,
    p1.deceased,
    p1.bad_email,
    p1.no_email,
    p1.notes AS notess,
    p1.referral,
    p1.location,
    p1.last_general_exam_provider,
    p1.last_general_exam,
    p1.created_stamp,
    p1.updated_stamp,
    p1.tax_exempt,
    p1.username,
    p1.password,
    p1.height,
    p1.weight,
    p1.social_history,
    p1.pcp_phone,
    p1.pcp_fax,
    p1.last_mamogram,
    p1.last_colon,
    p1.last_flushot,
    p1.clrx_preference,
    p1.marketing,
    p1.patient_insurance,
    p1.annual_colon,
    p1.annual_mamogram,
    p1.annual_flushot,
    p1.no_family_history,
    p1.no_problems,
    p1.target_iop_od,
    p1.target_iop_os,
    p1.sexual_orientation_details,
    p1.gender_identity_details,
    p1.tcpa_consent_given,
    p1.parent,
    p2.firstname AS guar_firstname,
    p2.lastname AS guar_lastname,
    p2.birthday AS guar_birthday,
    p2.married AS guar_married,
    p2.mi AS guar_mi,
    p2.sex AS guar_sex,
    p2.ssn AS guar_ssn,
    p2.designation AS guar_designation,
    p2.address AS guar_address,
    p2.city AS guar_city,
    p2.state AS guar_state,
    p2.zip AS guar_zip,
    p2.email AS guar_email,
    p2.homephone AS guar_homephone,
    p2.workphone AS guar_workphone,
    p2.cell AS guar_cell,
    ( SELECT array_agg(z.type) AS asd
           FROM communication_preferences z
          WHERE z.patient::text = p1.uid::text
          GROUP BY z.patient) AS prefs,
    ( SELECT pi.subscriber_relationship
           FROM pat_ins pi
          WHERE pi.patient::text = p1.uid::text AND pi.subscriber::text = p1.parent::text
         LIMIT 1) AS subscriber_relationship
   FROM patients p1
     LEFT JOIN patients p2 ON p1.parent::text = p2.uid::text;

ALTER TABLE public.v_source_patients
    OWNER TO postgres;

