-- View: public.v_migrated_patients

-- DROP VIEW public.v_migrated_patients;

CREATE OR REPLACE VIEW public.v_migrated_patients
 AS
 SELECT o.source_datasetid,
    o.source_instanceid,
    (o.target_model ->> '_id'::text) AS _id,
    (o.target_model ->> 'title'::text) AS title,
    (o.target_model ->> 'firstName'::text) AS firstname,
    (o.target_model ->> 'lastName'::text) AS lastname,
    (o.target_model ->> 'id'::text) AS id,
    (o.target_model ->> 'nickName'::text) AS nickname,
    (o.target_model ->> 'mrn'::text) AS mrn,
    (o.target_model ->> 'mi'::text) AS mi,
    ((o.target_model ->> 'dob'::text))::date AS dob,
    (o.target_model ->> 'age'::text) AS age,
    (o.target_model ->> 'sex'::text) AS sex,
    (o.target_model ->> 'ssn'::text) AS ssn,
    (o.target_model ->> 'notes_text'::text) AS notes_text,
    (((o.target_model -> 'address'::text) -> 0) ->> 'address_addressLine1'::text) AS address_addressline1,
    (((o.target_model -> 'address'::text) -> 0) ->> 'address_city'::text) AS address_city,
    (((o.target_model -> 'address'::text) -> 0) ->> 'address_state'::text) AS address_state,
    (((o.target_model -> 'address'::text) -> 0) ->> 'address_zip'::text) AS address_zip,
    (((o.target_model -> 'address'::text) -> 0) ->> 'address_badAddress'::text) AS address_badaddress,
    (o.target_model ->> 'contactPrefrence'::text) AS contactprefrence,
    ((o.target_model -> 'smokingHistory'::text) ->> 'smokingStatus'::text) AS smokinghistory_smokingstatus,
    ((o.target_model -> 'contactInformation'::text) ->> 'contactInformation_language'::text) AS contactinformation_language,
    ((o.target_model -> 'contactInformation'::text) ->> 'contactInformation_preferred'::text) AS contactinformation_preferred,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) ->> 'contactInformation.phones_type'::text) AS contactinformation_phones_type,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) ->> 'contactInformation.phones_phoneNumber'::text) AS contactinformation_phones_phonenumber,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) ->> 'contactInformation_phones_isPreferred'::text) AS contactinformation_phones_ispreferred,
    (((o.target_model -> 'contactInformation'::text) -> 'phones'::text) ->> 'contactInformation_phones_isBad'::text) AS contactinformation_phones_isbad,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) ->> 'contactInformation_emails_email'::text) AS contactinformation_emails_email,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) ->> 'contactInformation_emails_badEmail'::text) AS contactinformation_emails_bademail,
    (((o.target_model -> 'contactInformation'::text) -> 'emails'::text) ->> 'contactInformation_noEmail'::text) AS contactinformation_noemail,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_occupation'::text) AS patientdetails_occupation,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_maritalStatus'::text) AS patientdetails_maritalstatus,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_maidenName'::text) AS patientdetails_maidenname,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_sexualOrientation'::text) AS patientdetails_sexualorientation,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_genderIdentities'::text) AS patientdetails_genderidentities,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_employer'::text) AS patientdetails_employer,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_previousFirstName'::text) AS patientdetails_previousfirstname,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_previousLastName'::text) AS patientdetails_previouslastname,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_previousMiddleName'::text) AS patientdetails_previousmiddlename,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_race'::text) AS patientdetails_race,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_ethnicity'::text) AS patientdetails_ethnicity,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_isFlagNew'::text) AS patientdetails_isflagnew,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_isFlagInCollection'::text) AS patientdetails_isflagincollection,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_isFlagBadCheck'::text) AS patientdetails_isflagbadcheck,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_isFlagDeceased'::text) AS patientdetails_isflagdeceased,
    ((o.target_model -> 'patientDetails'::text) ->> 'patientDetails_isFlagChartless'::text) AS patientdetails_isflagchartless,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_firstName'::text) AS guarantor_firstname,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_lastName'::text) AS guarantor_lastname,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_dob'::text) AS guarantor_dob,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_maritalStatus'::text) AS guarantor_maritalstatus,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_middleName'::text) AS guarantor_middlename,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_relationship'::text) AS guarantor_relationship,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_sex'::text) AS guarantor_sex,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_ssn'::text) AS guarantor_ssn,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_title'::text) AS guarantor_title,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_address_addressLine1'::text) AS guarantor_address_addressline1,
    (((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'guarantor_address_city'::text) AS guarantor_address_city,
    (((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'guarantor_address_state'::text) AS guarantor_address_state,
    (((o.target_model -> 'guarantor'::text) -> 'address'::text) ->> 'guarantor_address_zip'::text) AS guarantor_address_zip,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_contactInformation_emails0_email'::text) AS guarantor_contactinformation_emails0_email,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_contactInformation_phones0_number'::text) AS guarantor_contactinformation_phones0_number,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_contactInformation_phones1_number'::text) AS guarantor_contactinformation_phones1_number,
    ((o.target_model -> 'guarantor'::text) ->> 'guarantor_contactInformation_phones2_number'::text) AS guarantor_contactinformation_phones2_number
   FROM v_migrated_objects o
  WHERE ((o.model)::text = 'patients'::text);

ALTER TABLE public.v_migrated_patients
    OWNER TO postgres;

