-- View: public.v_source_pat_app_loc_pro

-- DROP VIEW public.v_source_pat_app_loc_pro;

CREATE OR REPLACE VIEW public.v_source_pat_app_loc_pro
 AS
 SELECT pro.uid AS provider_uid,
    pro.prov_id AS provider_id,
    loc.uid AS location_uid,
    app.uid AS appointment_uid,
    app."time" AS app_time,
    app.date AS app_date,
    app.patient AS app_patient,
    app.provider_template AS app_provider_template,
    app.length AS app_length,
    app.confirmed AS app_confirmed,
    app.type AS app_type,
    app.notes AS app_notes,
    app.provider AS app_provider,
    p.uid AS p_uid,
    p.firstname AS p_firstname,
    p.lastname,
    p.mi,
    p.designation,
    p.workphone,
    p.homephone,
    p.address,
    p.city,
    p.state,
    p.zip,
    p.email,
    p.cell,
    p.ssn,
    p.birthday,
    p.occupation,
    p.employer,
    p.last_general_exam,
    p.last_general_exam_provider,
    p.notes,
    p.sex,
    p.referral,
    p.medicare_number,
    p.pat_med,
    p.fam_med,
    p.pat_eye,
    p.new_pat,
    p.married,
    p.location,
    p.bad_address,
    p.bad_phone,
    p.bad_email,
    p.collections,
    p.bad_check,
    p.deceased,
    p.marketing,
    p.no_call,
    p.patient_insurance,
    p.employee,
    p.parent,
    p.password,
    p.tax_exempt,
    p.pat_id,
    p.social_history,
    p.chartless,
    p.preferred_phone,
    p.preferred_name,
    p.preferred_language,
    p.race,
    p.ethnicity,
    p.height,
    p.weight,
    p.annual_colon,
    p.annual_mamogram,
    p.annual_flushot,
    p.no_email,
    p.username,
    p.smoking_status,
    p.preferred_contact,
    p.last_colon,
    p.last_flushot,
    p.last_mamogram,
    p.encrypted,
    p.pcp_phone,
    p.pcp_fax,
    p.no_family_history,
    p.no_problems,
    p.target_iop_od,
    p.target_iop_os,
    p.sexual_orientation,
    p.sexual_orientation_details,
    p.gender_identity,
    p.gender_identity_details,
    p.maiden_name,
    p.referral_source,
    p.previous_name_qualifier,
    p.previous_firstname,
    p.previous_lastname,
    p.previous_mi,
    p.clrx_preference,
    p.guarantor,
    p.tcpa_consent_given
   FROM (((appointments app
     LEFT JOIN patients p ON (((app.patient)::text = (p.uid)::text)))
     LEFT JOIN locations loc ON (((app.location)::text = (loc.uid)::text)))
     LEFT JOIN v_source_providers pro ON (((app.provider)::text = (pro.prov_id)::text)));

ALTER TABLE public.v_source_pat_app_loc_pro
    OWNER TO postgres;

