-- View: public.v_source_patients

-- DROP VIEW public.v_source_patients;

CREATE OR REPLACE VIEW public.v_source_patients
 AS
 SELECT patients.uid,
    patients.homephone,
    patients.workphone,
    patients.email,
    patients.cell,
    patients.designation,
    patients.firstname,
    patients.lastname,
    patients.pat_id,
    patients.preferred_name,
    patients.mi,
    patients.birthday,
    patients.sex AS sexs,
    patients.ssn,
    patients.address,
    patients.city,
    patients.state,
    patients.zip,
    patients.bad_address,
    patients.smoking_status,
    patients.no_call,
    patients.preferred_language,
    patients.preferred_contact,
    patients.preferred_phone,
    patients.bad_phone,
    patients.occupation,
    patients.married,
    patients.referral_source,
    patients.sexual_orientation,
    patients.gender_identity,
    patients.employer,
    patients.previous_firstname,
    patients.previous_lastname,
    patients.previous_mi,
    patients.race,
    patients.ethnicity,
    patients.new_pat,
    patients.collections,
    patients.bad_check,
    patients.chartless,
    patients.notes,
    patients.deceased,
    patients.bad_email,
    patients.no_email,
    ( SELECT string_agg((z.type)::text, ','::text ORDER BY z.updated_stamp DESC) AS asd
           FROM communication_preferences z
          WHERE ((z.patient)::text = (patients.uid)::text)
          GROUP BY z.patient) AS prefs,
    patients.notes AS notess,
    patients.referral,
    patients.location,
    patients.last_general_exam_provider,
    patients.last_general_exam,
    patients.created_stamp,
    patients.updated_stamp,
    patients.tax_exempt,
    patients.username,
    patients.password,
    patients.height,
    patients.weight,
    patients.maiden_name,
    patients.social_history,
    patients.pcp_phone,
    patients.pcp_fax,
    patients.last_mamogram,
    patients.last_colon,
    patients.last_flushot,
    patients.clrx_preference,
    patients.marketing,
    patients.patient_insurance,
    patients.annual_colon,
    patients.annual_mamogram,
    patients.annual_flushot,
    patients.no_family_history,
    patients.no_problems,
    patients.target_iop_od,
    patients.target_iop_os,
    patients.sexual_orientation_details,
    patients.gender_identity_details,
    patients.tcpa_consent_given
   FROM patients;

ALTER TABLE public.v_source_patients
    OWNER TO postgres;

