-- View: public.v_source_coverage

-- DROP VIEW public.v_source_coverage;

CREATE OR REPLACE VIEW public.v_source_coverage
 AS
 SELECT pi.uid,
    pi.created_stamp,
    pi.updated_stamp,
    pi.location_stamp,
    pi.insurance,
    pi.plan,
    pi.patient,
    pi.subscriber,
    pi.insurance_id,
    pi.subscriber_relationship,
    pi.group_number,
    pi.patins_type,
    pi.card_phone,
    pi.selected,
    pi.active,
    pi.deleted,
    pi.max_deductible,
    pi.cur_deductible,
    pi.max_oop,
    pi.cur_oop,
    pi.ordering,
    p.firstname,
    p.lastname,
    p.mi,
    p.designation,
    p.workphone,
    p.homephone,
    p.address,
    p.city,
    p.state,
    p.zip,
    p.email,
    p.cell,
    p.ssn,
    p.birthday,
    p.occupation,
    p.employer,
    p.last_general_exam,
    p.last_general_exam_provider,
    p.notes,
    p.sex,
    p.referral,
    p.medicare_number,
    p.pat_med,
    p.fam_med,
    p.pat_eye,
    p.new_pat,
    p.married,
    p.location,
    p.bad_address,
    p.bad_phone,
    p.bad_email,
    p.collections,
    p.bad_check,
    p.deceased,
    p.marketing,
    p.no_call,
    p.patient_insurance,
    p.employee,
    p.parent,
    p.password,
    p.tax_exempt,
    p.pat_id,
    p.social_history,
    p.chartless,
    p.preferred_phone,
    p.preferred_name,
    p.preferred_language,
    p.race,
    p.ethnicity,
    p.height,
    p.weight,
    p.annual_colon,
    p.annual_mamogram,
    p.annual_flushot,
    p.no_email,
    p.username,
    p.smoking_status,
    p.preferred_contact,
    p.last_colon,
    p.last_flushot,
    p.last_mamogram,
    p.encrypted,
    p.pcp_phone,
    p.pcp_fax,
    p.no_family_history,
    p.no_problems,
    p.target_iop_od,
    p.target_iop_os,
    p.sexual_orientation,
    p.sexual_orientation_details,
    p.gender_identity,
    p.gender_identity_details,
    p.maiden_name,
    p.referral_source,
    p.previous_name_qualifier,
    p.previous_firstname,
    p.previous_lastname,
    p.previous_mi,
    p.clrx_preference,
    p.guarantor,
    p.tcpa_consent_given,
    plan.insurance AS plan_insurance,
    plan.name,
    plan.plan_type,
    plan.address AS plan_address,
    plan.city AS plan_city,
    plan.state AS plan_state,
    plan.zip AS plan_zip,
    plan.phone1,
    plan.phone2,
    plan.fax,
    plan.benefits,
    plan.referral_required,
    plan.auth_required,
    plan.material_auth_required,
    plan.md_only,
    plan.notes AS plan_notes,
    plan.benefit_type,
    plan.pays_tax,
    plan.outside_lab,
    plan.payer_id,
    plan.available,
    plan.lab,
    plan.group_num_required,
    plan.typology_code,
    plan.medical_dx_required,
    plan.benefit_refresh_span,
    plan.benefit_refresh_units,
    plan.bill_refraction,
    plan.template,
    plan.voucher_required,
    plan.static_frame_covered,
    plan.finalized,
    plan.allowed_order_types,
    plan.sds_id,
    plan.book_page
   FROM ((pat_ins pi
     LEFT JOIN patients p ON ((((pi.patient)::text = (p.uid)::text) AND (pi.active = true))))
     LEFT JOIN insurance_plans plan ON (((pi.plan)::text = (plan.uid)::text)));

ALTER TABLE public.v_source_coverage
    OWNER TO postgres;

